import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Members only",
 description: "Generated by create next app",
};

export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en" data-theme="business">
   <body className={montserrat.className}>
    <Navigation />
    {children}
   </body>
  </html>
 );
}
